pre-release-replacements = [
  {file="README.md", search="releases/download/v[0-9\\.-]+", replace="releases/download/v{{version}}"},
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n\n## [Unreleased] - ReleaseDate"},
  {file="GithubAction-Dockerfile", search="FROM becheran/mlc:[0-9\\.-]+", replace="FROM becheran/mlc:{{version}}"},
]